### ISSUE TITLE
option for disabling ntp

### ISSUE THREAD

**Issue by johnnydtan** [boundary/bprobe_cookbook#14]
I would make a pull-request to put a flag for disabling bprobe's internal ntp in either `/etc/bprobe/bprobe.defaults` or `/etc/sysconfig/bprobe`, but it wouldn't matter because the init file (that comes installed with the bprobe package) would also need to be changed to read the flag and, if true, add `--disable-ntp` to the start options.

So this is a request to ask that `/etc/init.d/bprobe` be updated to include a conditional that if DISABLE_NTP (or something along those lines) is true, then add `--disable-ntp` to bprobe start options.

Probably someone else would want a flag to add in their own ntp pools too, so that might be another good addition while you're changing the init file.

p.s. Yes I could write a chef template that overrides the bprobe init, but the better solution is for the init script to already include all the possible bprobe options, honestly.

**Comment by ohlol** [comment]
We've got something for this in the pipeline, so gonna close :)

Thanks!

**Comment by johnnydtan** [comment]
Awesome, thank you.
