### ISSUE TITLE
Dangerous Use of Node.save

### ISSUE THREAD

**Issue by apeschel** [boundary/bprobe_cookbook#16]
Node.save will push the current node attribute to the chef server. Any cookbooks after bprobe in the runlist will not have had a chance to add their attributes to the node before this happens. This means the bprobe cookbook will clear the attributes on the chef server of any cookbook after it in the runlist until the entire chef run has completed.

This results in transient breakage, as any searches against the chef server for those attributes will return incorrect results until the entire chef run has completed.

The node.save code here should be reworked into something safer.

**Comment by apeschel** [comment]
Related issue for sysctl cookbook: https://github.com/acrmp/foodcritic/issues/235

**Comment by bhouse** [comment]
:+1:

**Comment by mfischer-zd** [comment]
:+1:

**Comment by damacus** [comment]
:+1:
