### ISSUE TITLE
Problem to migrate nodes between organizations using Chef

### ISSUE THREAD

**Issue by rafaelverger** [boundary/bprobe_cookbook#2]
I was facing some problems to change nodes from one org to another;
My first steps to do this:
- Changed my keys in chef role; failed
- Added recipe[bprobe:delete] before the default; failed
- Removed nodes from older org (they was offline already); faield

To finish the migration I was forced to access my node attributes (knife node edit NODE) and **manually delete** the whole attribute map `boundary` and remove the bprobe installation of each nodes (**apt-get purge bprobe**, using ubuntu on my nodes)

**Comment by ohlol** [comment]
Hi Rafael,

If you are still experiencing this problem, can you send an E-mail to support@boundary.com?

Thanks!

**Comment by rafaelverger** [comment]
@ohlol , I'm not using boundary anymore but I hope it is fixed
